# System-wide .bashrc file for interactive bash(1) shells.
if [ -z "$PS1" ]; then
   return
fi

### PS1='\h:\W \u\$ '
PS1='\033[01;33m\][kaifamiao]\033[01;34m\]\W \[\033[01;36m\]\$\[\033[00m\]'
# Make bash check its window size after a process completes
shopt -s checkwinsize

[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"
